version: '3.9'

services:
  database:
    image: postgres:latest
    container_name: cameltech
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cameltech
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata:
    driver: local
